spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sportsShop
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
  logging.level:
    org.hibernate.SQL: debug
jwt:
  key: klamk;mfodimi;om;ovfsmso;fvmvmiiroipefoi;ergjesrgseoijrgsjrijgsog;ijri;skg;dfsjgo